[package]
name = "homomorphic-encryption-project"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.4"
probability = "0.17.0"
num = { version = "0.4.0", features = ["rand"] }
sha2 = "0.10.2"